package fr.inria.diverse.torgen.inspectorguidget.xp;

import fr.inria.diverse.torgen.inspectorguidget.analyser.Command;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import org.jetbrains.annotations.NotNull;

public class NetbeansLauncher extends XPLauncher {

	public static void main(String args[]) {
		new NetbeansLauncher().run();
	}

	@Override
	protected List<String> getInputResoures() {
		return Arrays.asList("/media/data/dev/repoAnalysisBlob/main-silver/ant.browsetask/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/ant.debugger/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/ant.freeform/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/ant.grammar/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/ant.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.annotations.common/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.debugger/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.debugger.jpda/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.htmlui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.intent/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.io/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.java/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.java.classpath/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.knockout/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.maven/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.mobility/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.progress/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.progress.compat8/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.progress.nb/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.search/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.ant/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.apidocs/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.crudsample/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.feedreader/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.harness/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.installer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.installer.maven/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.osgidemo/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.paintapp/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.project/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.refactoring/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.restsample/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/apisupport.wizards/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.templates/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.visual/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.web.webmodule/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.xml/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/api.xml.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/applemenu/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/autoupdate.cli/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/autoupdate.pluginimporter/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/autoupdate.services/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/autoupdate.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/avatar_js.project/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/beans/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/bugtracking/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/bugtracking.bridge/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/bugtracking.commons/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/bugtracking.kenai/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/bugzilla/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/bugzilla.exceptionreporter/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/classfile/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/clearcase/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cloud.amazon/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cloud.common/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cloud.oracle/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.analysis.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.analysis.impl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.antlr/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.api.model/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.api.project/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.api.remote/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.api.remote.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.apt/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.asm/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.callgraph/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.classview/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.cncppunit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.completion/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.debugger.common2/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.debugger.gdb2/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.discovery/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.dwarfdiscovery/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.dwarfdump/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.editor/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.gotodeclaration/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.highlight/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.indexing/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.lexer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.makeproject/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.makeproject.source.bridge/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.makeproject.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.mixeddev/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.modeldiscovery/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.modelimpl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.model.jclank.bridge/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.model.services/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.modelui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.modelutil/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.navigation/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.qnavigator/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.refactoring/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.remote/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.remote.projectui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.remote.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.repository/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.repository.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.script/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.search/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.simpleunit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.source/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.spellchecker.bindings/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.testrunner/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.toolchain/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.toolchain.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.utils/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/cnd.utils.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/code.analysis/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/coherence/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/collab.channel.chat/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/collab.channel.chat.html/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/collab.channel.chat.java/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/collab.channel.chat.text/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/collab.channel.chat.xml/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/collab.channel.filesharing/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/collab.channel.output/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/collab.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/collab.provider.im/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/collab.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/cordova/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/cordova.platforms/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/cordova.platforms.android/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/cordova.platforms.ios/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/core.browser/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/core.browser.webview/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/core.browser.webview.jfxplatformbridge/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.execution/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.ide/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.io.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.multitabs/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.multitabs.project/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.multiview/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.nativeaccess/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.netigso/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.network/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.osgi/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.output2/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.startup/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.startup.base/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/core.windows/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/c.s.collablet/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/c.s.collablet.moxc/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/csl.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/csl.types/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/css.editor/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/css.lib/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/css.model/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/css.prep/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/css.visual/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/db/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/dbapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/db.core/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/db.dataview/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/db.drivers/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/db.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/db.metadata.model/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/db.mysql/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/db.mysql.sakila/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/dbschema/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/db.sql.editor/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/db.sql.visualeditor/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/deadlock.detector/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.ant/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.heapwalk/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.js/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.jsui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.projects/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.projectsui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.truffle/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.trufflenode/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/debugger.jpda.visual/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/defaults/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/deployment.deviceanywhere/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/deployment.wm/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/derby/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/diff/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/dlight.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/dlight.libs.common/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/dlight.nativeexecution/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/dlight.nativeexecution.nb/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/dlight.remote/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/dlight.remote.impl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/dlight.remote.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/dlight.sendto/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/dlight.terminal/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/docker.api/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/docker.editor/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/docker.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.actions/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.bookmarks/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.bracesmatching/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.breadcrumbs/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.codetemplates/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.completion/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.deprecated.pre65formatting/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.document/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.errorstripe/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.errorstripe.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.fold/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.fold.nbui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.global.format/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.guards/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.indent/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.indent.project/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.indent.support/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.lib/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.lib2/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.macros/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.mimelookup/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.mimelookup.impl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.plain/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.plain.lib/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.search/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.settings/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.settings.lib/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.settings.storage/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.structure/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.tools.storage/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/editor.util/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/el.lexer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/extbrowser/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/extbrowser.chrome/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/extexecution/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/extexecution.base/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/extexecution.impl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/extexecution.process/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/extexecution.process.jdk9/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/favorites/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/findbugs/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/findbugs.installer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/form/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/form.binding/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/form.j2ee/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/form.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/form.nb/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/form.refactoring/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/git/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/git.remote/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/git.remote.cli/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/glassfish.cloud/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/glassfish.common/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/glassfish.eecommon/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/glassfish.javaee/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/glassfish.tooling/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/gototest/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/groovy.antproject/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/groovy.editor/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/groovy.grails/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/groovy.grailsproject/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/groovy.gsp/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/groovy.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/groovy.refactoring/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/groovy.samples/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/groovy.support/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/gsf.codecoverage/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/gsf.testrunner/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/gsf.testrunner.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hibernate/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hibernate4lib/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hibernatelib/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hibernateweb/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/html/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/html.angular/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/html.custom/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/html.editor/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/html.editor.lib/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/html.knockout/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/html.lexer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/html.ojet/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/html.parser/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/html.validation/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/httpserver/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hudson/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hudson.ant/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hudson.git/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hudson.maven/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hudson.mercurial/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hudson.php/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hudson.subversion/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hudson.tasklist/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/hudson.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/i18n/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/i18n.form/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/ide.branding/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/ide.branding.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/ide.ergonomics/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/ide.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/identity.ant/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/identity.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/identity.profile.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/identity.profile.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/identity.samples/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/identity.server.manager/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/image/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.ant/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.api.ejbmodule/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2eeapis/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.clientproject/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.common/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.core/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.core.utilities/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.dd/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.ddloaders/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.dd.webservice/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.earproject/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.eclipselink/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.eclipselinkmodelgen/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.ejbcore/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.ejbjarproject/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.ejbrefactoring/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.ejbverification/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.genericserver/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.jboss4/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.jpa.refactoring/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.jpa.verification/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.metadata/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.metadata.model.support/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.persistence/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.persistenceapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.persistence.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.platform/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.samples/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2eeserver/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.sun.appsrv/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.sun.appsrv81/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.sun.dd/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.sun.ddui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.toplinklib/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.weblogic9/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2ee.websphere6/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.platform/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.platform.bdj/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.platform.nokias80/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.platform.nsicom/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.platform.ojec/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.platform.ricoh/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.platform.semc/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.platform.sjmc/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.platform.sun/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project.bdj/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project.execui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project.execuiimpl/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project.nokiaS80/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project.nsicom/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project.ojec/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project.ricoh/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project.savaje/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project.semc/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.cdc.project.sjmc/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.common.ant/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.keystore/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/j2me.project/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.api.common/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.apdufile/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.apdu.io/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.common/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.console/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.filemodels/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.oberthur/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.platform.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.project/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.ri.bundle/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.ri.platform/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javacard.spi/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.completion/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.debug/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/javadoc/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.editor/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.editor.base/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.editor.lib/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javaee7.api/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javaee.api/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javaee.beanvalidation/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javaee.injection/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javaee.project/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javaee.resources/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javaee.specs.support/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javaee.wildfly/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/java.examples/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/java.freeform/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/javafx2.editor/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/javafx2.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/javafx2.platform/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/javafx2.project/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/javafx2.samples/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/javafx2.scenebuilder/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.graph/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.guards/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/javahelp/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.hints/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.hints.declarative/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.hints.declarative.test/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.hints.legacy.spi/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.hints.test/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.hints.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.j2sedeploy/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.j2seembedded/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.j2semodule/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.j2seplatform/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.j2seprofiles/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.j2seproject/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.lexer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.metrics/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.module.graph/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.navigation/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.platform/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.platform.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.preprocessorbridge/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.project/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.project.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.debug/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.debug.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.doc/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.editor/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.extdoc/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.extjs/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.jade/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.jquery/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.jsdoc/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.json/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.knockout/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.lexer/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.model/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.nodejs/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.prototypejs/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.react/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.requirejs/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.sdoc/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.source.query/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript2.types/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript.bower/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript.cdnjs/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript.grunt/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript.gulp/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript.jstestdriver/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript.karma/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript.nodejs/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript.v8debug/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/javascript.v8debug.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.source/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.source.ant/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.source.base/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.source.compat8/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.source.queries/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.source.queriesimpl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.sourceui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.testrunner/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.testrunner.ant/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/java.testrunner.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/javawebstart/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/javax.wsdl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jconsole/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jellytools.cnd/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jellytools.enterprise/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jellytools.ide/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jellytools.java/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jellytools.platform/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jemmy/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jira/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jira.rest/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jira.xmlrpc/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jmx/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jmx.common/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jshell.support/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jsp.lexer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/jumpto/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/junit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/junit.ant/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/junit.ant.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/junitlib/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/junit.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/kenai/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/kenai.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/kenai.maven/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/kenai.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/keyring/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/keyring.fallback/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/keyring.impl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/keyring.jps/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/ko4j.debugging/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/languages/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/languages.apacheconf/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/languages.diff/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/languages.ini/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/languages.manifest/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/languages.neon/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/languages.refactoring/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/languages.yaml/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/lexer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/lexer.nbbridge/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.cvsclient/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.jshell.agent/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.nbjavac/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.nbjshell/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.profiler/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.profiler.charts/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.profiler.common/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.profiler.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.aguiswinglayout/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.amazon/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.antlr3.devel/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.antlr3.runtime/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.antlr4.runtime/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.asm/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.bytelist/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.cglib/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.clank/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.commons_compress/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.commons_fileupload/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.commons_net/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.dbx/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.elimpl/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.felix/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.findbugs/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.freemarker/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.git/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.glassfish_logging/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.groovy/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.ini4j/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.javacapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.javacimpl/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.javacup/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.javafx/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.jaxb/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.jira.rest/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.jna/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.jna.platform/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.jsch.agentproxy/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.jshell/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.json_simple/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.jsr223/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.jstestdriver/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.jstl/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.junit4/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.jvyamlb/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.lucene/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.nashorn/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.nbi.ant/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.nbi.engine/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.oracle.cloud/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.osgi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.plist/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.ppawtlayout/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.smack/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.springframework/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.svnClientAdapter/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.svnClientAdapter.javahl/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.svnClientAdapter.svnkit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.swingx/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.testng/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.wag/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.xerces/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/libs.xmlbeans/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.terminalemulator/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.uihandler/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/lib.v8debug/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/loadgenerator/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/localhistory/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/localtasks/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/masterfs/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/masterfs.linux/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/masterfs.macosx/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/masterfs.nio2/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/masterfs.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/masterfs.windows/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.apisupport/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.checkstyle/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.coverage/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.embedder/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.grammar/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.graph/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.groovy/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.hints/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.indexer/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.indexer.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.j2ee/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.jaxws/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.junit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.junit.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.model/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.osgi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.persistence/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.profiler/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.refactoring/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.repository/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.samples/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.search/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.spring/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/maven.util/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mercurial/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mercurial.remote/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mercurial.search/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.antext/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.cldcplatform/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.cldcplatform.catalog/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.databindingme/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.deployment.ftpscp/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.deployment.nokia/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.deployment.ricoh/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.deployment.sonyericsson/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.deployment.webdav/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.editor/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.end2end/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.j2meunit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.jsr172/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.licensing/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.midpexamples/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.plugins.mpowerplayer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.project/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.project.ant/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.project.bridge/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.project.bridge.impl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.svgcore/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mobility.wtk_win/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mvd/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/mylyn.util/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/nashorn.execution/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/netserver/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/notifications/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs.cnd/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs.git/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs.hudson/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs.mercurial/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs.subversion/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs.tasks/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs.tasks.bridge/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/odcs.versioning/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.bluej/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.bluej.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.bootstrap/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.core/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.insane/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.mobility.lib.activesync/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.swing.dirchooser/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.swing.laf.dark/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.swing.outline/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.swing.plaf/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.swing.tabcontrol/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/o.n.upgrader/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/o.openidex.util/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.actions/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.awt/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.compat/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.dialogs/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.execution/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.execution.compat8/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.explorer/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.filesystems/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.filesystems.compat8/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.filesystems.nb/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.io/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.loaders/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.modules/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.nodes/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.options/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.text/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.util/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.util.enumerations/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.util.lookup/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.util.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/openide.windows/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/options.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/options.editor/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/options.java/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/options.keymap/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/parsing.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/parsing.indexing/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/parsing.lucene/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/parsing.nb/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/parsing.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/performance/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/performance.ergonomics/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/performance.java/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/performance.javaee/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/performance.scripting/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/performance.web/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.api.annotation/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.api.documentation/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.api.editor/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.api.executable/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.api.framework/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.apigen/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.api.phpmodule/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.api.templates/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.api.testing/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.atoum/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.code.analysis/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.codeception/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.composer/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.dbgp/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.doctrine2/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.editor/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.latte/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.nette2/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.nette.tester/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.phing/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.phpdoc/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.phpdoc.documentation/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.phpunit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.project/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.refactoring/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.samples/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.smarty/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.symfony/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.symfony2/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.twig/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.zend/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/php.zend2/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/print/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/print.editor/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.attach/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.commandrunner/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.freeform/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.heapwalker/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.j2ee/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.j2se/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.loadgen/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.nbimpl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.nbmodule/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.options/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.oql/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.oql.language/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.ppoints/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.projectsupport/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.snaptracer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/profiler.utilities/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/progress.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/project.ant/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/project.ant.compat8/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/project.ant.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/projectapi/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/projectapi.nb/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/projectimport.eclipse.core/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/projectimport.eclipse.j2se/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/projectimport.eclipse.web/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/projectimport.jbuilder/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/project.indexingbridge/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/project.libraries/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/project.libraries.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/project.spi.intern/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/project.spi.intern.impl/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/projectui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/projectuiapi/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/projectuiapi.base/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/projectui.buildmenu/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/properties/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/properties.based.dataobjects/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/properties.syntax/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/queries/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/refactoring.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/refactoring.java/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/remotefs.versioning/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/remotefs.versioning.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/sampler/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/schema2beans/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/selenium2/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/selenium2.java/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/selenium2.maven/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/selenium2.php/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/selenium2.server/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/selenium2.webclient/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/selenium2.webclient.mocha/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/selenium2.webclient.protractor/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/sendopts/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/server/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/servletapi/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/servletjspapi/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/settings/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/simple.project.templates/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spellchecker/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spellchecker.apimodule/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spellchecker.bindings.htmlxml/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spellchecker.bindings.java/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spellchecker.bindings.php/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spellchecker.bindings.properties/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spellchecker.dictionary_en/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spellchecker.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.actions/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.debugger.jpda.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.debugger.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.editor.hints/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.editor.hints.projects/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.java.hints/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.navigator/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.palette/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.quicksearch/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.tasklist/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spi.viewmodel/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spring.beans/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/spring.webmvc/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/subversion/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/subversion.remote/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/svg.perseus/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/swingapp/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/swingapplib/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/swing.customizerlayout/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/swing.validation/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/target.iterator/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/tasklist.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/tasklist.projectint/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/tasklist.todo/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/tasklist.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/team.commons/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/team.ide/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/team.server/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/team.server.nb/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/templates/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/templatesui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/terminal/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/terminal.nb/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/testng/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/testng.ant/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/testng.maven/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/testng.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/timers/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/tomcat5/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/traceio/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/uihandler/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/uihandler.exceptionreporter/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/uihandler.interactive/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/updatecenters/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/usersguide/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/utilities/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/utilities.project/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/versioning/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/versioning.core/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/versioning.indexingbridge/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/versioning.kenai/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/versioning.masterfs/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/versioning.system.cvss/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/versioning.system.cvss.installer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/versioning.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/versioning.util/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.analyzer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.codegen/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.components.midp/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.components.midp.pda/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.components.midp.wma/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.componentssupport/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.components.svg/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.examples/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.flow/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.game/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.inspector/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.io/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.io.javame/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.kit/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.midp/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.midp.converter/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.midpnb/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.model/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.palette/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.properties/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.screen/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/vmd.structure/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.beans/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.browser.api/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.client.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.clientproject/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.clientproject.api/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.client.rest/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.client.samples/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.common/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.common.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.core/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.core.syntax/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.debug/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.domdiff/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.el/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.facelets010114/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.fake/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.freeform/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.indent/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.inspect/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.javascript.debugger/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsf/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsf12/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsf12ri/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsf20/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsfapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsf.editor/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsf.extensions/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsf.icefaces/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsf.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsf.navigation/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jsf.richfaces/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.jspparser/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.livehtml/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/weblogic.common/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.monitor/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.primefaces/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.project/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.refactoring/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websocket/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.struts/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.axis2/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.clientapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.core/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.customization/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.design/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.editor.hints/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.jaxrpc/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.jaxrpc16/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.jaxrpckit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.jaxws21/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.jaxws21api/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.jaxwsapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.jaxws.lightapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.jaxwsmodel/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.jaxwsmodelapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.manager/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.metro.lib/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.metro.model/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.metro.samples/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.owsm/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.projectapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.registry/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.rest/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.restapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.restkit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.restlib/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.rest.samples/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.rest.wadl.design/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.rest.wadl.model/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.api/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.codegen/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.codegen.j2ee/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.codegen.java/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.codegen.php/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.kit/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.amazon/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.delicious/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.flickr/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.google/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.strikeiron/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.twitter/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.weatherbug/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.yahoo/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.youtube/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.zillow/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.services.zvents/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.saas.ui/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.utilities/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.websvcapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.wsitconf/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.wsitmodelext/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/websvc.wsstackapi/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.webkit.debugging/src",
//			"/media/data/dev/repoAnalysisBlob/main-silver/web.webkit.tooling/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/welcome/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/whitelist/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.axi/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.catalog/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.catalog.ui/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.core/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.jaxb/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.jaxb.api/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.lexer/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.multiview/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.retriever/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.schema.completion/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.schema.model/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.tax/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.text/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.text.obsolete90/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.tools/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.tools.java/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.wsdl.model/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.xam/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xml.xdm/src",
			"/media/data/dev/repoAnalysisBlob/main-silver/xsl"
		);
	}

	@Override
	protected String[] getSourceClassPath() {
		return new String[]{};
	}

	@Override
	protected @NotNull List<Command> filterBlobsToRefactor() {
		List<ListenerID> ids = Arrays.asList(
			new ListenerID("StylePanelFigMessage.java", 98),
			new ListenerID("StylePanelFigPackage.java", 87),
			new ListenerID("WizStep.java", 269),
			new ListenerID("UMLAddDialog.java", 253),
			new ListenerID("FindDialog.java", 402),
			new ListenerID("StylePanelFigText.java", 273),
			new ListenerID("StylePanelFigNodeModelElement.java", 152),
			new ListenerID("StylePanelFigUseCase.java", 96),
			new ListenerID("StylePanelFigInterface.java", 80),
//			new ListenerID("WizStepChoice.java", 143),
			new ListenerID("CriticBrowserDialog.java", 480),
//			new ListenerID("CriticBrowserDialog.java", 423),
			new ListenerID("StylePanelFigClass.java", 111)
		);

		return blobAnalyser.getBlobs().entrySet().stream().
			filter(e -> ids.stream().anyMatch(id -> id.match(e.getKey()))).
			map(e -> e.getValue()).flatMap(s -> s.getCommands().stream()).collect(Collectors.toList());
	}

	@Override
	protected int getCompilianceLevel() {
		return 7;
	}

	@Override
	protected boolean usingLambda() {
		return false;
	}

	@Override
	protected String getOutputFolder() {
		return "/media/data/dev/refactor/netbeans";
	}
}
